name: darto
description: Darto is a lightweight and flexible microframework inspired by Express for building web applications in Dart.
version: 0.0.1
homepage: https://github.com/evandersondev/darto

environment:
  sdk: ^3.7.1

dependencies:
  path: ^1.9.1
  mime: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
