name: darto
description: Darto is a microframework inspired by Express and Fastify for building web applications in Dart.
version: 0.0.6
homepage: https://github.com/evandersondev/darto

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  path: ^1.9.1
  mime: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
